# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Chronicle' do
	pod 'SWXMLHash', '~> 2.1'
	pod 'RealmSwift', '~> 0.98'
	pod 'SDWebImage', '~> 3.7'
	pod 'pop', '~> 1.0'
	pod 'JSON', '~> 4.0'
end

target 'ChronicleTests' do

end

target 'ChronicleUITests' do

end

