# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Chronicle' do
	pod 'FBSDKLoginKit', '~> 4.9'
	pod 'AEXML', '~> 2.1'
	pod 'RealmSwift', '~> 0.98'
	pod 'RealmMapView'	
end

target 'ChronicleTests' do

end

target 'ChronicleUITests' do

end

